FROM openjdk:17-ea-11-jdk-slim

VOLUME /tmp

RUN apt-get update && apt-get upgrade -y && apt-get install curl -y

#COPY ecommerce.jks ecommerce.jks
COPY build/libs/config-server-0.0.1-SNAPSHOT.jar ConfigServer.jar

ENTRYPOINT ["java","-jar","ConfigServer.jar"]